### ISSUE TITLE
Превью картинки в низком разрешение занимает меньше места чем картинка в оригинальном разрешение

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/geekr#110]
**Описание бага**

на примере статьи https://habra.vercel.app/company/gms/blog/565638

![image](https://user-images.githubusercontent.com/26829359/127174882-4aa8edd4-ed62-4cb2-a37d-4d8ac920a116.png)

![image](https://user-images.githubusercontent.com/26829359/127174952-d6633cc8-b800-4e56-b8d8-43f7b21a7585.png)

после прогрузки картинка занимает больше места чем превью

**Comment by jarvis394** [comment]
wontfix
