### ISSUE TITLE
Сломанная верстка

### ISSUE THREAD

**Issue by lpite** [jarvis394/geekr#146]
**Описание бага**
появляется скролл 

**Шаги для повторения бага**
1. без понятия 

**Ожидаемый результат**
появляется скролл

**Скриншоты**
![image](https://user-images.githubusercontent.com/67955038/135609989-f8278bce-4fa1-4aa0-bd40-b9e4a95cce4d.png)
**Информация об устройстве:**
 - OS: 14.6
 - Браузер: firefox
 - Версия браузера: [последняя]

**Комментарий**
Здесь можно написать что-нибудь дополнительно по проблеме.

**Comment by jarvis394** [comment]
Возможно, зависит от браузера. У меня скролл не появляется.

**Comment by lpite** [comment]
скорей всего но на iphone как я помню движок у всех одинаковый поэтому будет так везде

**Comment by jarvis394** [comment]
Поставил firefox: скролла нет. Возможно, у вас был скролл до этого (на предыдущем экране)? Проблема появляется всегда?

**Comment by lpite** [comment]
я перезагрузил и попробовал в другом браузере именно в этой статье теги вылазят

**Comment by lpite** [comment]
нет(

**Comment by jarvis394** [comment]
Максимально печально...

**Comment by lpite** [comment]
хотя стоп пофиксилось простите

**Comment by jarvis394** [comment]
Ура!
