### ISSUE TITLE
Предотвратить постоянную отправку запросов для проверки наличия соединения

### ISSUE THREAD

**Issue by MrZillaGold** [jarvis394/geekr#150]
**Референс**

Component: https://github.com/MrZillaGold/Steve-VKMiniApps/blob/master/src/components/Offline.jsx
Hook: https://github.com/MrZillaGold/Steve-VKMiniApps/blob/master/src/hooks/online.js

**Comment by jarvis394** [comment]
> браузер явно поддерживает нативное определение через navigator или ивенты.

В доках у react-detect-offline написано:

> [1] Polling is only used as a fallback for browsers that don't support the "online" event. Currently these are Chrome on Windows, Firefox on Windows, and Chrome on Linux.

Не знаю, почему так, но наверное есть причина, почему они считают, что в хроме нет нативной реализации.

**Comment by MrZillaGold** [comment]
> В доках у react-detect-offline написано:

Поправлял свой последний ответ, скорее всего  не заметили. Это делает Sentry.
