### ISSUE TITLE
500 ошибка

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/geekr#160]
Не отображаются статьи и новости с 500 ошибкой

**Скриншоты**

![Screenshot_20211219_150512_com.android.chrome.jpg](https://user-images.githubusercontent.com/26829359/146668067-2cda129c-63cc-4820-a34f-b56323df53b6.jpg)

**Comment by jarvis394** [comment]
![image](https://user-images.githubusercontent.com/37776763/146672701-22ab595a-f1dd-4cd1-81b1-1b1971c6c423.png)

упал сервер :(

**Comment by jarvis394** [comment]
Починил, сервер перезапустился и сбросил настройки PM2
