### ISSUE TITLE
Приглядывание текста между блоками

### ISSUE THREAD

**Issue by centralhardware** [jarvis394/geekr#162]
**Описание

Поверх блока с заголовком статьи виден текст. Буквально пару пикселей 

**Скриншоты**
![image](https://user-images.githubusercontent.com/26829359/148490298-a3807933-f3b5-4060-a2b1-1bdb22b6e7b2.png)

**Информация об устройстве:**
 - OS: iPadOS 15.02
 - Браузер: Google chrome 
 - Версия браузера: latest

**Comment by centralhardware** [comment]
Между строкой состояния и блоком с заголовком виден набор пикселей. На картинке не видно но если скролить то видно что там отображается текст и пиксели меняются в зависимости от текста и того смог ли ты попасть на строчку

**Comment by jarvis394** [comment]
Привет! Похоже на проблему webkit'a на IOS, тут как бы мои полномочия все 😶

Несколько уточняющих вопросов:
1. Проявляется ли до сих пор проблема?
2. Проявляется ли проблема при показанной строки URL в хроме (когда на экране есть верхний бар с полем для URL и меню)
3. Проявляется ли проблема в Safari?
4. Проблема присутствует на всех экранах с этим элементом или появляется периодически?

Пока что попробую добавить заливку на -1px.
