### ISSUE TITLE
Ошибка при переходе к чтению статьи или новости.

### ISSUE THREAD

**Issue by igk1972** [jarvis394/geekr#165]
На всех устройствах возникает ошибка при переходе от списка к чтению статьи или новости.

`
TypeError: Cannot read properties of undefined (reading 'articleIds')
`

**Comment by igk1972** [comment]
Fix in PR https://github.com/jarvis394/geekr/pull/166

**Comment by jarvis394** [comment]
Принял PR. Спасибо!

(поздно заметил ошибку, т.к. сдаю сессию сейчас 😓)
