### ISSUE TITLE
Замена ссылок с habr.com не работает

### ISSUE THREAD

**Issue by tsunamaru** [jarvis394/geekr#192]
**Описание бага**
Уже какое-то время не работает замена ссылок в статьях и комментах с habr.com на geekr.vercel.app

**Шаги для повторения бага**
1. Включить соответствующую опцию в настройках сайта
2. Попробовать открыть любую ссылку ведущую на хабр

**Ожидаемый результат**
Редирект на geekr

**Информация об устройстве:**
 - OS: без разницы
 - Браузер: любой
 - Версия браузера: [последняя]

**Comment by jarvis394** [comment]
Жесть, не могу выложить пока что билд, потому что проект не собирается xdd

Слишком старые библиотеки стоят :/
