### ISSUE TITLE
Всё сломалось

### ISSUE THREAD

**Issue by tsunamaru** [jarvis394/geekr#193]
**Описание бага**
Пропали все статьи с главной кроме новостей, открытие новостей выпадает с ошибкой

**Шаги для повторения бага**
1. Открыть geekr 

**Ожидаемый результат**
Все работает

**Скриншоты**
![IMG_1823](https://github.com/jarvis394/geekr/assets/37580200/28f1d185-0576-4032-9ba6-5314f57f0b17)
![IMG_1824](https://github.com/jarvis394/geekr/assets/37580200/4a0de633-0357-481d-8b3a-2f121845570c)
![IMG_1825](https://github.com/jarvis394/geekr/assets/37580200/46fa8c62-e344-47ab-ac2c-35f4e6efdfba)

**Информация об устройстве:**
 - OS: iOS 17
 - Браузер: Safari
 - Версия браузера: [последняя]

**Комментарий**
Почините пожалусто, я после geekr уже не могу открывать обычный хабр.

**Comment by yuriizinets** [comment]
Хабр сменил фильтры, сортинг и в месте с этим ещё и апи. Теперь нормальные параметры спрятали под авторизацию. Новые настройки ленты, мягко говоря, не очень. Видимо, последний раз как я зашёл на хабр 🫡

**Comment by jarvis394** [comment]
С последнего раза, как я заходил в проект, накопилось 400 ошибок eslint и ts :/

Большинство починил, пытаюсь сейчас починить билд на vercel

**Comment by h45hc47** [comment]
> нужно очистить кеш приложения в настройках сайта в браузере
Не нашёл такого пункта в настройках, не подскажете, где он?

**Comment by jarvis394** [comment]
> Не нашёл такого пункта в настройках, не подскажете, где он?

На ПК: нажать на замочек в адресной строке -> Настройки сайта -> Удалить данные

На мобилке: нажать на замочек в адресной строке -> Куки и данные сайта -> Удалить данные

**Comment by tsunamaru** [comment]
@jarvis394 тут еще баг после починки вылез - если открывать ссылку на любую статью в новой странице (например через зажатый ctrl/cmd), то вместо этого открывается главная страница.
