### ISSUE TITLE
При открытии поста по ссылке переходит на главную

### ISSUE THREAD

**Issue by tinted-knight** [jarvis394/geekr#195]
**Описание бага**
При переходе по ссылке post/{id} открывается главная https://geekr.vercel.app/top/daily/p/1

**Шаги для повторения бага**

1. Перейти по ссылке https://geekr.vercel.app/post/782112

**Ожидаемый результат**
Открывается статья

**Информация об устройстве:**

- OS: macOS 13.3.1
- Браузер: Firefox 
- Версия браузера: 120.0.1

**Comment by tinted-knight** [comment]
upd: Сделал форк, поднял локально и всё работает корректно. Развернул на vercel (https://geekr-flame.vercel.app/) и вопсроизводится та же проблема, что описана в issue. Пока хз, что делать. Возможно в хостинге? Возможно в dev mode как-то по-другому обрабатываются пути?

**Comment by jarvis394** [comment]
К такому же выводу пришёл, пока что нет времени разбираться с Vercel :(

**Comment by tinted-knight** [comment]
Спс, если будет время попробую тоже поразбираться)

**Comment by John3812** [comment]
Я исправил это: 
https://github.com/John3812/geekr-fixed
Проблема была в том что, по сути SPA приложение обрабатывалось как статический сайт.
Т.е. сервер пытается найти директории на диске не находит и отправляет на главную.
Demo
gkr.onrender.com

**Comment by jarvis394** [comment]
@John3812 а где вы хоститесь? Vercel как раз на любой паттерн запроса отдает index.js от SPA, позволяя таким образом получать начальный путь. В настройках Vercel я вроде как не нашёл ничего, чтобы меняло это поведение.

Возможно, Vercel по разному обрабатывает запросы, если выбирать разные пресеты у приложения (был create-react-app, стал Vite)

**Comment by John3812** [comment]
@jarvis394 бесплатный NodeJS хостинг
https://render.com
Установка через docker.

У вас **vite** сервер, верно? Локально он у меня тоже работал нормально но на сервере та же проблема была.
Поэтому поменял на **serve** с ключом '-s'.
Скрипт запуска в _package.json_
`"start": "serve -s dist -l tcp://0.0.0.0:10000"`
